image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
before_script:
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY_FILE_PROD
  - gcloud config set project $GCP_PROJECT_PROD

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://pole-emploi-trad.firebaseapp.com
  script:
    - cd /builds/petranslate/petranslate-back-gcp/translation-app-assessment/backend/reporting
    - gcloud builds submit . --region=europe-west2
    - cd /builds/petranslate/petranslate-back-gcp/translation-app-assessment/backend/token-broker
    - gcloud builds submit . --region=europe-west2
    - cd /builds/petranslate/petranslate-back-gcp/translation-app-assessment/backend/cleanup
    - gcloud builds submit . --region=europe-west2
  only:
    refs:
      - master
