image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
before_script:
  - apk add --no-cache curl bash
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - sh -c '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
  - nvm install 21.7.3 # Remplacez 14 par la version de Node.js que vous souhaitez utiliser
  - nvm use 21.7.3
  - nvm alias default 21.7.3
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY_FILE
  - gcloud config set project $GCP_PROJECT
stages:
  - deploy
deploy-job:
  stage: deploy
  environment:
    name: staging
  script:
    #- cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/translation
    #- gcloud builds submit .
    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/reporting
    - gcloud builds submit .
    #- cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/token-broker
    #- gcloud builds submit .
    #- cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/cleanup
    #- gcloud builds submit .
    #- cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/telemetry
    #- gcloud builds submit .
    #- cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/authentication
    #- gcloud builds submit .
    #- cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/detect-text
    #- gcloud builds submit .
    #- cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/pdf-to-image
    #- gcloud builds submit .
  only:
    refs:
      - open-source
