image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
before_script:
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY_FILE
  - gcloud config set project $GCP_PROJECT

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: staging
    url: https://pole-emploi-trad-dev.firebaseapp.com
  script:
    - cd /builds/petranslate/petranslate-back-gcp/translation-app-assessment/backend/reporting
    - gcloud builds submit .
    - cd /builds/petranslate/petranslate-back-gcp/translation-app-assessment/backend/token-broker
    - gcloud builds submit .
    - cd /builds/petranslate/petranslate-back-gcp/translation-app-assessment/backend/cleanup
    - gcloud builds submit .
  only:
    refs:
      - develop
