image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
before_script:
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY_FILE_OPEN_SOURCE
  - gcloud config set project $GCP_PROJECT_OPEN_SOURCE
stages:
  - deploy
deploy-job:
  stage: deploy
  environment:
    name: open-source
  script:
#    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/translation
#    - gcloud builds submit .
#    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/reporting
#    - gcloud builds submit .
#    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/token-broker
#    - gcloud builds submit .
    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/cleanup
    - gcloud builds submit .
#    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/telemetry
#    - gcloud builds submit .
#    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/authentication
#    - gcloud builds submit .
#    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/detect-text
#    - gcloud builds submit .
#    - cd /builds/petranslate/TradEmploi-backend/translation-app-assessment/backend/pdf-to-image
#    - gcloud builds submit .
  only:
    refs:
      - master
