image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
before_script:
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY_FILE
  - gcloud config set project $GCP_PROJECT
stages:
  - deploy
deploy-job:
  stage: deploy
  environment:
    name: staging
  script:
    - cd /builds/translate/TradEmploi-backend/translation-app-assessment/backend/translation
    - gcloud builds submit .
    # - cd /builds/translate/TradEmploi-backend/translation-app-assessment/backend/reporting
    # - gcloud builds submit .
    # - cd /builds/translate/TradEmploi-backend/translation-app-assessment/backend/token-broker
    # - gcloud builds submit .
    # - cd /builds/translate/TradEmploi-backend/translation-app-assessment/backend/cleanup
    # - gcloud builds submit .
    # - cd /builds/translate/TradEmploi-backend/translation-app-assessment/backend/telemetry
    # - gcloud builds submit .
    # - cd /builds/translate/TradEmploi-backend/translation-app-assessment/backend/authentication
    # - gcloud builds submit .
  only:
    refs:
      - develop
