---
# Copyright 2020 Google LLC. This software is provided as-is, without warranty
# or representation for any use or purpose. Your use of it is subject to your
# agreement with Google.
steps:
  # Étape pour installer les dépendances npm
  - name: node:12 # Utilisez une image Node.js appropriée
    entrypoint: /bin/sh
    args:
      - '-c'
      - 'cd /workspace && npm install cors cookie-parser'
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$_IMAGE_TAG'
      - '--builder=gcr.io/buildpacks/builder:v1'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$_IMAGE_TAG'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$_IMAGE_TAG'
      - --platform=managed
      - --region=europe-west1
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$_IMAGE_TAG,gcb-build-id=$BUILD_ID,$_LABELS
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$_IMAGE_TAG'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LABELS: scope=poc
  _GCR_HOSTNAME: eu.gcr.io
  _SERVICE_NAME: trad-cleanup
  _DEPLOY_REGION: europe-west1
  _IMAGE_TAG: v1
  _PORT: '8080'
tags:
  - trad
